const views=[...document.querySelectorAll(".view")],nav=[...document.querySelectorAll(".nav")];
function go(id){views.forEach(v=>v.classList.toggle("active",v.id===id));nav.forEach(n=>n.classList.toggle("active",n.dataset.go===id));window.scrollTo({top:0,behavior:"smooth"});}
document.querySelectorAll("[data-go]").forEach(el=>el.addEventListener("click",()=>go(el.dataset.go)));

const now=new Date();
document.querySelector("#dateLabel").textContent=now.toLocaleDateString(undefined,{weekday:"long",month:"short",day:"numeric"});
document.querySelector("#greeting").textContent=now.getHours()<12?"Good morning.":now.getHours()<18?"Good afternoon.":"Good evening.";
if(localStorage.getItem("jarvis-theme")==="dark")document.body.classList.add("dark");
document.querySelector("#themeBtn").addEventListener("click",()=>{document.body.classList.toggle("dark");localStorage.setItem("jarvis-theme",document.body.classList.contains("dark")?"dark":"light");});

const STORIES=[
{category:"HISTORY × GEOGRAPHY",read:"~3 min",title:"1816: the year summer disappeared",teaser:"A volcano in Indonesia helped create crop failures, summer snow and a very strange year thousands of kilometres away.",body:["In April 1815, Mount Tambora on the Indonesian island of Sumbawa erupted with extraordinary force. Material from the eruption reached high into the atmosphere.","The following year became famous in parts of Europe and North America as the “Year Without a Summer.” Temperatures fell, harvests suffered and unusual cold appeared during months that should have been warm.","During a cold, rainy stay near Lake Geneva, Mary Shelley spent more time indoors with other writers and began the story that became Frankenstein."],fact:"A physical event in Southeast Asia influenced weather and culture on the other side of the world.",why:"It is a vivid example of how climate, geography, food supply and human history are connected.",place:"📍 Mount Tambora · Sumbawa, Indonesia",quiz:{q:"Mount Tambora is in which country?",choices:["Japan","Indonesia","Italy"],a:1,explain:"Indonesia — on the island of Sumbawa."}},
{category:"GEOGRAPHY",read:"~2 min",title:"Why the Himalayas are still rising",teaser:"The tallest mountain range on Earth is not finished being built.",body:["India was once part of a landmass far south of Asia. Over tens of millions of years, the Indian tectonic plate moved north and collided with the Eurasian plate.","Neither continent easily slid beneath the other, so huge sections of crust crumpled and thickened. That process built the Himalayas and the Tibetan Plateau.","The plates are still moving today. That continuing collision slowly changes the mountains and contributes to earthquake risk in the region."],fact:"Mountains can look permanent on a human timescale while still changing geologically.",why:"The collision helps explain the shape of South Asia, its earthquake risk and major regional climate patterns.",place:"📍 Himalayan range · South and Central Asia",quiz:{q:"Which two major plates created the Himalayas?",choices:["Indian and Eurasian","Pacific and African","Arabian and Antarctic"],a:0,explain:"The Indian Plate collided with the Eurasian Plate."}},
{category:"HISTORY",read:"~3 min",title:"The canal that redrew global trade",teaser:"A narrow strip of water in Egypt changed how Europe and Asia connected.",body:["Before the Suez Canal opened in 1869, ships travelling between Europe and much of Asia commonly had to sail around the southern tip of Africa.","The canal created a direct water route between the Mediterranean Sea and the Red Sea, shortening many voyages and making Egypt a critical shipping crossroads.","When the canal is blocked or disrupted, shipping schedules, insurance costs and supply chains far beyond Egypt can be affected."],fact:"A relatively narrow artificial waterway can influence trade across multiple continents.",why:"Transport geography often matters as much as distance itself. Chokepoints can shape economics and geopolitics.",place:"📍 Suez Canal · Egypt",quiz:{q:"The Suez Canal connects the Mediterranean to which sea?",choices:["Black Sea","Red Sea","Arabian Sea"],a:1,explain:"The Red Sea."}},
{category:"GEOGRAPHY",read:"~2 min",title:"A country that keeps making new land",teaser:"The Netherlands has spent centuries turning shallow water into usable land.",body:["Large parts of the Netherlands sit at or below sea level. Dutch engineers developed systems of dikes, pumps and drainage works to control water.","One famous method created polders: areas enclosed by dikes where water is pumped out and carefully managed.","Water management became an ongoing national project involving engineering, planning and institutions that must keep operating."],fact:"Some Dutch communities stand on land that was once underwater.",why:"It shows how geography is not always something people merely adapt to; sometimes societies actively reshape it.",place:"📍 The Netherlands · North Sea coast",quiz:{q:"What is a polder?",choices:["A reclaimed low-lying area","A mountain pass","A tidal island"],a:0,explain:"A low-lying tract enclosed by dikes and managed by drainage."}},
{category:"HISTORY × GEOGRAPHY",read:"~3 min",title:"Why cities appeared along rivers",teaser:"The map of early civilization makes much more sense when you look at water.",body:["Many early large societies developed around major river systems: the Nile, Tigris and Euphrates, Indus and Yellow River are famous examples.","Rivers supplied fresh water, fertile floodplains, transport routes and irrigation. Those advantages could support larger populations and more specialized work.","But rivers also created risk. Floods could destroy crops and settlements, so managing water encouraged organized labour, engineering and administration."],fact:"The same river could be a civilization’s greatest resource and one of its biggest threats.",why:"Physical geography helped shape where dense societies formed and what kinds of institutions they needed.",place:"📍 Nile · Tigris–Euphrates · Indus · Yellow River",quiz:{q:"Which benefit did rivers commonly provide early cities?",choices:["Reliable irrigation","Permanent snow cover","Natural oil pipelines"],a:0,explain:"Irrigation was one of the major advantages."}},
{category:"GEOGRAPHY",read:"~2 min",title:"The lake holding about one-fifth of Earth’s unfrozen fresh surface water",teaser:"Lake Baikal is far more than just a very deep lake.",body:["Lake Baikal in Siberia is the world’s deepest lake and contains an enormous volume of freshwater.","Its basin is ancient and tectonically active, which helped create its extraordinary depth. Long isolation also allowed many distinctive species to evolve there.","Because of its age, depth and biodiversity, Baikal is valuable not just geographically but scientifically."],fact:"By volume, Baikal contains roughly one-fifth of the world’s unfrozen surface freshwater.",why:"A single geographic feature can be globally important for water, biodiversity and Earth science at the same time.",place:"📍 Lake Baikal · Siberia, Russia",quiz:{q:"What makes Lake Baikal especially unusual?",choices:["It is the deepest lake","It is made of saltwater","It sits on the equator"],a:0,explain:"Baikal is the world’s deepest lake."}},
{category:"HISTORY",read:"~3 min",title:"The road network that helped hold Rome together",teaser:"Roman roads were infrastructure, logistics and political control rolled into one.",body:["Rome built an extensive network of roads across its territories. Moving soldiers, officials and information efficiently was a core reason.","Good roads made distant regions easier to govern and defend. Trade and civilian travel then benefited from the same infrastructure.","Centuries later, some European routes still follow corridors shaped by Roman roads."],fact:"Infrastructure can shape movement patterns long after the original political system disappears.",why:"Roads can determine which cities grow, where trade flows and how power travels.",place:"📍 Roman road network · Europe, North Africa and Western Asia",quiz:{q:"What was a major reason Rome built roads?",choices:["Moving armies and officials","Avoiding all sea travel","Creating ski routes"],a:0,explain:"Fast movement of armies, officials and messages was crucial."}},
{category:"GEOGRAPHY",read:"~2 min",title:"Why time zones are political as well as geographic",teaser:"The Sun does not create neat one-hour bands on a map. Governments do.",body:["Local solar time changes continuously as you move east or west, but modern transport and communication made thousands of local times impractical.","Standard time zones simplified railways, business and communication. Yet their borders rarely follow perfect lines of longitude.","Countries choose time standards for economic, administrative and political reasons, which is why time-zone maps contain surprising bends and exceptions."],fact:"Two places at similar longitudes can use different official times because governments choose their time zones.",why:"Even something that feels purely scientific can be shaped by borders, economics and social choices.",place:"📍 Global time-zone map",quiz:{q:"Why are time-zone borders irregular?",choices:["Political and administrative choices","The Moon changes them daily","Longitude stops at borders"],a:0,explain:"Governments choose official time standards, so borders are not purely geometric."}},
{category:"HISTORY × GEOGRAPHY",read:"~3 min",title:"How the Panama Canal changed the shape of a voyage",teaser:"One cut across Central America removed thousands of kilometres from many sea routes.",body:["Before the Panama Canal, ships travelling between the Atlantic and Pacific often had to go around South America.","The canal opened in 1914 and created a much shorter route across the Isthmus of Panama. Locks lift and lower ships because it is not simply a sea-level trench.","Its location turned Panama into a crucial point in global logistics, and canal capacity continues to affect shipping decisions."],fact:"Ships crossing Panama are lifted above sea level and then lowered again using locks.",why:"A small piece of geography can completely change the economics of global distance.",place:"📍 Panama Canal · Panama",quiz:{q:"The canal connects which two oceans?",choices:["Atlantic and Pacific","Indian and Arctic","Pacific and Southern"],a:0,explain:"The Atlantic and Pacific Oceans."}},
{category:"GEOGRAPHY",read:"~2 min",title:"The invisible line that changed every map",teaser:"Longitude needed a shared starting point. The world eventually chose one near London.",body:["Latitude has a natural reference at the Equator, but longitude needed people to agree on where zero degrees should be.","In 1884, an international conference adopted the meridian passing through Greenwich as the prime meridian used for global longitude.","That decision helped standardize navigation, mapping and timekeeping."],fact:"Zero degrees longitude is a human convention, not a natural feature of Earth.",why:"Maps look objective, but many parts of mapping depend on standards that societies agree to use.",place:"📍 Greenwich · London, United Kingdom",quiz:{q:"What longitude is the Prime Meridian?",choices:["0°","90°","180°"],a:0,explain:"0° longitude."}},
{category:"HISTORY",read:"~3 min",title:"The Silk Roads were never just one road",teaser:"One of history’s most famous routes was really a shifting network across continents.",body:["The term Silk Roads describes many interconnected land and sea routes linking regions of Asia, the Middle East, Africa and Europe.","Goods such as silk, spices, metals and glass moved through these networks, often changing hands many times rather than travelling with one merchant from start to finish.","Ideas, religions, technologies and diseases also travelled, making the network culturally important as well as economic."],fact:"A product could cross thousands of kilometres even when no single trader travelled the whole distance.",why:"Networks matter more than simple point-to-point routes when you want to understand how cultures and economies influence one another.",place:"📍 Eurasia · multiple overland and maritime routes",quiz:{q:"The Silk Roads were best described as what?",choices:["A network of routes","One paved highway","A single Roman road"],a:0,explain:"They were a broad network of routes."}},
{category:"GEOGRAPHY",read:"~2 min",title:"Why Chile looks impossibly long",teaser:"A narrow country stretches along the Pacific for thousands of kilometres because mountains and ocean shaped its geography.",body:["Chile occupies a long strip between the Pacific Ocean and the Andes Mountains along South America’s western edge.","Its north-to-south length crosses dramatically different climates, from the Atacama Desert to cool, wet southern landscapes and fjords.","That unusual shape means people can remain in the same country while moving through environments that feel like completely different parts of the world."],fact:"Chile’s geography compresses extreme climatic variety into one narrow national corridor.",why:"Country shape can affect transport, regional identity, infrastructure costs and access to resources.",place:"📍 Chile · western South America",quiz:{q:"Which mountain range runs along Chile’s eastern side?",choices:["Andes","Alps","Himalayas"],a:0,explain:"The Andes."}}
];

const todayIndex=Math.floor(new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime()/86400000)%STORIES.length;let shown=todayIndex;
function renderStory(i){shown=(i+STORIES.length)%STORIES.length;const s=STORIES[shown];document.querySelector("#storyCategory").textContent=s.category;document.querySelector("#storyReadTime").textContent=s.read;document.querySelector("#storyTitle").textContent=s.title;document.querySelector("#storyBody").innerHTML=s.body.map(p=>"<p>"+p+"</p>").join("");document.querySelector("#storyFact").textContent=s.fact;document.querySelector("#storyWhy").textContent=s.why;document.querySelector("#storyPlace").textContent=s.place;document.querySelector("#quizQuestion").textContent=s.quiz.q;document.querySelector("#quizChoices").innerHTML=s.quiz.choices.map((c,n)=>'<button data-quiz="'+n+'">'+c+"</button>").join("");document.querySelector("#quizAnswer").textContent="";document.querySelector("#homeDiscoverTitle").textContent=s.title;document.querySelector("#homeDiscoverTeaser").textContent=s.teaser;document.querySelector("#storyDayLabel").textContent=shown===todayIndex?"Today’s selection":"Bonus story";document.querySelectorAll("[data-quiz]").forEach(b=>b.addEventListener("click",()=>{document.querySelector("#quizAnswer").textContent=Number(b.dataset.quiz)===s.quiz.a?"Correct — "+s.quiz.explain:"Not quite — "+s.quiz.explain;}));}
renderStory(todayIndex);document.querySelector("#anotherStory").addEventListener("click",()=>renderStory(shown+1));

function timeAgo(v){const d=new Date(v);if(Number.isNaN(d.getTime()))return"";const m=Math.max(0,Math.round((Date.now()-d.getTime())/60000));if(m<60)return m+"m ago";const h=Math.round(m/60);return h<24?h+"h ago":Math.round(h/24)+"d ago";}
function cleanSummary(s,t){s=(s||"").trim();return(!s||s===t)?"Open Briefly for the full saved summary.":s;}
async function loadBriefly(){const status=document.querySelector("#brieflyStatus"),list=document.querySelector("#brieflyList");try{const r=await fetch("../Briefly/data.json?ts="+Date.now(),{cache:"no-store"});if(!r.ok)throw 0;const d=await r.json(),stories=(d.stories||[]).slice(0,8);document.querySelector("#homeNewsCount").textContent=stories.length;document.querySelector("#brieflyUpdatedHome").textContent=d.updated?timeAgo(d.updated):"Live";status.textContent=d.updated?"Updated "+timeAgo(d.updated):"Live feed";if(stories[0]){document.querySelector("#homeTopStory").textContent=stories[0].title;document.querySelector("#homeTopStoryMeta").textContent=(stories[0].cat||"News")+" · "+(stories[0].source||"Briefly");}list.innerHTML=stories.map(s=>'<article class="news-item glass"><div class="news-meta"><span class="news-badge">'+esc((s.icon||"")+" "+(s.cat||"News"))+'</span><span>'+esc(timeAgo(s.publishedAt||s.published))+'</span></div><h3>'+esc(s.title||"Untitled")+'</h3><p>'+esc(cleanSummary(s.summary,s.title))+'</p><div class="news-source">'+esc(s.source||"")+'</div></article>').join("")||'<div class="empty-state">No current stories.</div>';}catch{status.textContent="Could not reach Briefly";list.innerHTML='<div class="empty-state">Your standalone Briefly app is still available from the link above.</div>';}}
loadBriefly();

const KEY="jarvis-lab-projects-v1";function projects(){try{return JSON.parse(localStorage.getItem(KEY)||"[]")}catch{return[]}}function save(a){localStorage.setItem(KEY,JSON.stringify(a))}
function projectName(idea){const skip=new Set(["i","want","an","a","app","that","where","to","build","make","for","me"]);const w=idea.replace(/[^a-zA-Z0-9\s-]/g," ").trim().split(/\s+/).filter(x=>x&&!skip.has(x.toLowerCase())).slice(0,4);return w.length?w.map(x=>x[0].toUpperCase()+x.slice(1)).join(" "):"New Project";}
function renderProjects(){const a=projects(),box=document.querySelector("#projectsList");document.querySelector("#homeProjectCount").textContent=a.length;if(!a.length){box.innerHTML='<div class="empty-state">No saved projects yet. Your next idea starts above.</div>';return}box.innerHTML=a.map((p,i)=>'<article class="project glass"><div class="project-top"><div><small>IDEA · '+esc(p.date)+'</small><h3>'+esc(p.name)+'</h3></div><button data-del="'+i+'">×</button></div><p>'+esc(p.idea)+'</p></article>').join("");document.querySelectorAll("[data-del]").forEach(b=>b.addEventListener("click",()=>{const x=projects();x.splice(Number(b.dataset.del),1);save(x);renderProjects()}));}
document.querySelector("#startBuild").addEventListener("click",()=>{const el=document.querySelector("#idea"),idea=el.value.trim();if(!idea)return;const a=projects();a.unshift({name:projectName(idea),idea,date:new Date().toLocaleDateString(undefined,{month:"short",day:"numeric"})});save(a.slice(0,30));el.value="";renderProjects();});document.querySelector("#clearProjects").addEventListener("click",()=>{save([]);renderProjects()});renderProjects();

async function checkRouter(){
  const base=String(window.JARVIS_API||"").replace(/\/$/,"");
  if(!base)return;
  try{
    const res=await fetch(base+"/health");
    const data=await res.json();
    document.querySelector("#pGemini").textContent="Gemini "+(data.providers?.gemini?"●":"○");
    document.querySelector("#pGroq").textContent="Groq "+(data.providers?.groq?"●":"○");
    document.querySelector("#pOpenRouter").textContent="OpenRouter "+(data.providers?.openrouter?"●":"○");
    const pill=document.querySelector(".router-pill");
    if(pill)pill.textContent="Router online";
  }catch{}
}
checkRouter();

const conversation=[];
document.querySelector("#askForm").addEventListener("submit",async e=>{
  e.preventDefault();
  const el=document.querySelector("#askInput"),v=el.value.trim();
  if(!v)return;
  const c=document.querySelector("#chat");
  c.insertAdjacentHTML("beforeend",'<div class="message user">'+esc(v)+'</div>');
  conversation.push({role:"user",content:v});
  el.value="";
  const base=String(window.JARVIS_API||"").replace(/\/$/,"");
  if(!base){
    c.insertAdjacentHTML("beforeend",'<div class="message jarvis">The secure router code is ready, but its Cloudflare URL is not connected yet.</div>');
    return;
  }
  const wait=document.createElement("div");
  wait.className="message jarvis";
  wait.textContent="Thinking…";
  c.appendChild(wait);
  try{
    const res=await fetch(base+"/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:conversation})});
    const data=await res.json();
    if(!res.ok)throw new Error(data.error||"Router error");
    wait.textContent=data.text||"No response";
    conversation.push({role:"assistant",content:data.text||""});
    const pill=document.querySelector(".router-pill");
    if(pill)pill.textContent=(data.provider||"AI")+" · free";
  }catch(err){
    wait.textContent="Jarvis could not reach a free model: "+(err.message||err);
  }
});
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));}